url: "https://cupor.soc.srcf.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "CUPor" # the name of your site, e.g. ACME Corp.
sass:
  style: compressed
nav_dropdowns:
  - about.md
  - constitution.md
  - committee.html

