baseURL: 'http://www.cupor.uk'
languageCode: 'en-gb'
title: 'CUPor'

params:
  description: CUPor is a society at the University of Cambridge that brings together members of the University that are Portuguese or are interested in Portuguese culture.

